apiVersion: v1
kind: Service
metadata:
  name: todo-api
  annotations:
    "prometheus.io/scrape": "true"
  labels:
    run: todo-api
spec:
  type: ClusterIP
  ports:
    - name: http
#      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app: todo-api
