[build]
target-dir = 'dist/target'
[env]
# Scope down tracing, to filter out external lib tracing.
PORT = "8080"
RUST_LOG = "info"
RUST_ENV = "development"
# DB's - must be set
MONGO_URI = "mongodb://localhost:27017"
REDIS_HOST = "redis://localhost:6379"
DATABASE_URL = "postgres://myuser:mypassword@localhost/mydatabase"
INFLUXDB_URL = "http://localhost:8086"
INFLUXDB_TOKEN = "admintoken123"
INFLUXDB_ORG_ID = "docs"
#SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"
#
#SERVICE_PWD_KEY = "CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"
#
#SERVICE_TOKEN_KEY = "9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw"
#SERVICE_TOKEN_DURATION_SEC = "1800" # 30 minutes
#
### -- ConfigMap

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.
SERVICE_WEB_FOLDER = "web-folder/"
