docker_build(
  "yurikrupnik/todo-api",
  "../..",
  dockerfile="../../rust.Dockerfile",
  build_args={"APP_NAME":"todo_api"},
  target="final",
  ignore=["./k8s", "../../manifests", "./migrations"],
)

k8s_resource("todo-api", port_forwards="5201:8080")
