docker_build(
  "yurikrupnik/web-playground",
  "../..",
  dockerfile="../../rust.Dockerfile",
  build_args={"APP_NAME":"todo_api"},
  target="final",
  ignore=["k8s", "../../manifests", "../../platform"],
)
k8s_resource("web-playground", port_forwards="5201:8080")
#k8s_yaml(kustomize('manifests/kustomize/overlays/dev'))
#k8s_resource("web-playground", port_forwards="5201:8080")
